### ISSUE TITLE
Database oh database

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeData#191]
Dear all,

I am setting up the final docker machines and such. I'm having problems with the database initialization. I created a docker container that executes the build line:

```
npm run build --collection=pokemon
```

The logs after the execution are:

``` bash
[pokedataBASHdevelop-1]2016-10-23T02:41:22.780492421Z npm info it worked if it ends with ok 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.780735592Z npm info using npm@2.14.2 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.780917768Z npm info using node@v4.0.0 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.962375385Z npm info prebuild pokemongo-api@0.0.1 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.966944876Z npm info build pokemongo-api@0.0.1 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.968729799Z  
[pokedataBASHdevelop-1]2016-10-23T02:41:22.968743226Z > pokemongo-api@0.0.1 build /usr/src/app 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.968747122Z > NODE_ENV=production node scripts/build.js 
[pokedataBASHdevelop-1]2016-10-23T02:41:22.968750306Z  
[pokedataBASHdevelop-1]2016-10-23T02:41:24.912365411Z npm info postbuild pokemongo-api@0.0.1 
[pokedataBASHdevelop-1]2016-10-23T02:41:24.916616405Z npm info ok
```

But as you can see, the result is pretty different:

http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/api/pokemon/
vs
https://api.predictemall.online/api/pokemon/

Any idea? The stack file in case someone wonders:

``` yml
catchtemalldevelop:
  autoredeploy: true
  environment:
    - API_ENDPOINT=api.predictemall.online
    - WEBSOCKET_ENDPOINT=api.predictemall.online:65024
  image: 'pokemongoers/catch-em-all:develop'
  ports:
    - '6010:8080'
mongo:
  image: 'mongo:latest'
pokedataINITdevelop:
  autoredeploy: true
  command: npm run build --collection=pokemon
  environment:
    - ACCESS_TOKEN=########
    - ACCESS_TOKEN_KEY=########
    - CONSUMER_KEY=########
    - CONSUMER_SECRET=########
    - MLAB_COLLECTION=pokemongo
    - MLAB_URI=mongo
  image: 'pokemongoers/pokedata:develop'
  links:
    - mongo
pokedatadevelop:
  autoredeploy: true
  environment:
    - ACCESS_TOKEN=########
    - ACCESS_TOKEN_KEY=########
    - CONSUMER_KEY=########
    - CONSUMER_SECRET=########
    - MLAB_COLLECTION=pokemongo
    - MLAB_URI=mongo
  image: 'pokemongoers/pokedata:develop'
  links:
    - mongo
  ports:
    - '4050:8080'
    - '3322:65024'
pokedatatwitterdevelop:
  autoredeploy: true
  command: npm run listen --collection=twitter
  environment:
    - ACCESS_TOKEN=########
    - ACCESS_TOKEN_KEY=########
    - CONSUMER_KEY=########
    - CONSUMER_SECRET=########
    - MLAB_COLLECTION=pokemongo
    - MLAB_URI=mongo
  image: 'pokemongoers/pokedata:develop'
  links:
    - mongo
```
